version: '3'

services:
  API:
    image: 'wailram/api'
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - CODERUNNER
      - AUTH
    environment:
      - DATASOURCE_URL=jdbc:mariadb://mysql-moodlelight.alwaysdata.net/moodlelight_data
      - DATASOURCE_USERNAME=257118_api
      - DATASOURCE_PASSWORD=vivespring
  CODERUNNER:
    image: 'wailram/runner'
    container_name: coderunner
  AUTH:
    image: 'wailram/security'
    container_name: auth
    environment:
      - DATASOURCE_URL=jdbc:mariadb://mysql-moodlelight.alwaysdata.net/moodlelight_data
      - DATASOURCE_USERNAME=257118_yann
      - DATASOURCE_PASSWORD=yannforner
